#!/bin/bash

## Tools that will be used
# Subfinder
# Amass
# Assetfinder
# Findomain
# Anew
# Filter-Resolved
# ShuffleDNS
# Dnsgen
# Httpx

## Banner
function banner() {
    echo ""
    echo "_____ ___________"
    echo "/  ___|  ___|  ___|"
    echo "\  -- | |__ | |_"
    echo "  --  \  __||  _ |"
    echo "/\__/ / |___| |"
    echo "\____/\____/\_| @remonsec"
    echo "Subdomain Enumeration Framework"
}

## Variables 
domain=$1

## Function
function Passive() {
    subfinder -d $domain -o subfinder.txt -all
    assetfinder --subs-only $domain | sort -u > assetfinder.txt
    amass enum -passive -norecursive -noalts -d $domain -config /root/.config/amass/config.ini -o amass.txt
    findomain -t $domain -u findomain.txt
    cat subfinder.txt assetfinder.txt amass.txt findomain.txt | sort -u > passive.txt
    rm subfinder.txt assetfinder.txt amass.txt findomain.txt
}
function Active() {
    shuffledns -d $domain -w /root/wordlist/all.txt -r /root/wordlist/resolvers.txt -o active_tmp.txt
    cat active_tmp.txt | sed 's/*.//' > active.txt
    rm active_tmp.txt
}
function ActPsv() {
    cat active.txt passive.txt | sort -u | filter-resolved > active_passive.txt
    rm active.txt passive.txt
}
function Permute() {
    if [[ $(cat active_passive.txt | wc -l) -le 50 ]]
    then
        dnsgen active_passive.txt | shuffledns -d $domain -r /root/wordlist/resolvers.txt -o permute1.txt
        dnsgen permute1.txt | shuffledns -d $domain -r /root/wordlist/resolvers.txt -o permute2.txt
        cat permute1.txt permute2.txt | sort -u | filter-resolved > permute.txt
        rm permute1.txt permute2.txt
    elif [[ $(cat active_passive.txt | wc -l) -le 500 ]]
    then
        dnsgen active_passive.txt | shuffledns -d $domain -r /root/wordlist/resolvers.txt -o permute.txt
    else
        echo "[#] No Permutation"
    fi
}
function SubFinal() {
    cat *.txt | sort -u > sub.txt
}
function Htpx() {
    httpx -l sub.txt -silent -o sub.httpx
    httpx -l sub.txt -csp-probe -silent | grep ".$domain" | anew sub.httpx
}
function sefresult() {
    echo ""
    echo "[#] Total Subdomain Found $(cat sub.txt | wc -l)"
    echo "[#] Total HTTPx Found $(cat sub.httpx | wc -l)"
}

## Logic
Passive 
Active
ActPsv
Permute
SubFinal
Htpx
sefresult