#!/bin/bash

## Tools that will be used
# Subfinder
# Amass
# Assetfinder
# Findomain
# Anew
# ShuffleDNS
# Dnsgen
# Httpx

## Banner
function banner() {
    echo "
    ░██████╗███████╗███████╗░░░░░░░██████╗░██╗░░░██╗██╗░█████╗░██╗░░██╗
    ██╔════╝██╔════╝██╔════╝░░░░░░██╔═══██╗██║░░░██║██║██╔══██╗██║░██╔╝
    ╚█████╗░█████╗░░█████╗░░█████╗██║██╗██║██║░░░██║██║██║░░╚═╝█████═╝░
    ░╚═══██╗██╔══╝░░██╔══╝░░╚════╝╚██████╔╝██║░░░██║██║██║░░██╗██╔═██╗░
    ██████╔╝███████╗██║░░░░░░░░░░░░╚═██╔═╝░╚██████╔╝██║╚█████╔╝██║░╚██╗
    ╚═════╝░╚══════╝╚═╝░░░░░░░░░░░░░░╚═╝░░░░╚═════╝░╚═╝░╚════╝░╚═╝░░╚═╝"
    echo ""
    echo  "       @remonsec @KathanP19"
    echo "Subdomain Enumeration Framework"
}

## Variables 
domain=$1

## Function
function format_time() {
    ((h=${1}/3600))
    ((m=(${1}%3600)/60))
    ((s=${1}%60))
    printf "%02d:%02d:%02d\n" $h $m $s
}

function Passive() {
    subfinder -d $domain -o subfinder.txt -all
    assetfinder --subs-only $domain | sort -u > assetfinder.txt
    amass enum -passive -norecursive -noalts -d $domain -config /root/.config/amass/config.ini -o amass.txt
    findomain -t $domain -u findomain.txt
    cat subfinder.txt assetfinder.txt amass.txt findomain.txt | grep -F ".$domain" | sort -u > passive.txt
    rm subfinder.txt assetfinder.txt amass.txt findomain.txt
}

function Htpx() {
    httpx -l passive.txt -silent -o sub.httpx
    httpx -l passive.txt -csp-probe -silent | grep -F ".$domain" | anew sub.httpx
    httpx -l passive.txt -tls-probe -silent | grep -F ".$domain" | anew sub.httpx
}


### Footer Text ###
function sefresult() {
    echo ""
    echo ""
    echo "[#] Total Subdomain Found $(cat passive.txt | wc -l)"
    echo "[#] Total HTTP Probed Found $(cat sub.httpx | wc -l)"
    echo "[/] Script completed in total $(format_time $SECONDS)"
}

function text1() {
    echo ""
    echo ""
    echo "// Running Passive Enumeration on $domain"
}

function text2() {
    sleep 2
    echo "// Running Httpx on $domain"
}

## Logic
banner
text1
Passive &>/dev/null
text2
Htpx &>/dev/null
sefresult