#!/bin/bash
echo ""
echo "_____ ___________"
echo "/  ___|  ___|  ___|"
echo "\  -- | |__ | |_"
echo "  --  \  __||  _ |"
echo "/\__/ / |___| |"
echo "\____/\____/\_| @remonsec"
echo "Subdomain Enumeration Framework"

echo ""
echo "[#] Running Subenum for passive enumeration"
echo ""
subenum -d $1 -o $1.passive
echo ""
echo "[#] Running sub.sh for passive enumeration"
sub -a $1
cat $1.txt | sort -u >> $1.passive
echo ""
echo "[#] Running ShuffleDns for active enumeration"
echo ""
shuffledns -d $1 -w /root/wordlist/all.txt -r /root/wordlist/resolvers.txt -strict-wildcard -o $1.active
echo ""
echo "[#] Gathering Active & Passive subdomains"
cat $1.passive $1.active | filter-resolved | sort -u > $1.active_passive
echo ""
echo "[#] Running dnsgen & shuffledns for permute enumeration"
dnsgen $1.active_passive | shuffledns -d $1 -r /root/wordlist/resolvers.txt -o $1.permute.tmp
echo ""
echo "[#] Gathering all enumeation result in one file"
cat $1.permute.tmp | filter-resolved | sort -u > $1.permute.tmp1
echo ""
echo "[#] Running dnsgen & shuffledns for 2nd permute enumeration"
dnsgen $1.permute.tmp1 | shuffledns -d $1 -r /root/wordlist/resolvers.txt -o $1.permute.tmp2
echo ""
echo "[#] Gathering all enumeation result in one file"
cat $1.active_passive *tmp* | filter-resolved | sort -u > $1.sub
cat *tmp* | sort -u | filter-resolved > $1.permute
echo ""
echo "[#] Running Subfinder recursive enumeration"
subfinder -dL $1.sub -recursive -silent -o $1.sub.recursive
cat $1.sub.recursive | anew $1.sub
echo ""
echo "[#] Removing extra files"
rm $1.active_passive *tmp* $1.txt httprobe_* no_resolve_*
echo ""
echo ""
echo "Running HTTPX over final output"
httpx -l $1.sub -o $1.httpx.sub
echo ""
echo "Running HTTPX CSP over final output"
cat $1.sub | httpx -csp-probe -silent | grep ".$1" | tee $1.httpx.csp
echo ""
echo "Gathering all HTTPX files in one file"
cat $1.httpx.sub $1.httpx.csp | sort -u > $1.httpx
echo ""
echo "[#] Removing extra files"
rm $1.httpx.sub $1.httpx.csp
echo ""
echo "Total Subdomain Found [ $(cat $1.sub | wc -l) ]"
echo "Total Httpx domain Found [ $(cat $1.httpx | wc -l) ]"
echo "[#] Cool, Subdomain enumeration Done !"